### ISSUE TITLE
OTX error message

### ISSUE THREAD

**Issue by Wulluby** [keithjjones/hostintel#10]
Hello, I am getting an OTX error, looks like an unexpected 404 response. FWIW, OTX seems to work fine with fileintel.

$ python hostintel.py hiconfig.conf myhosts -a > hiout.csv
*** Processing sergiocarfagna.it ***
ERROR:  An exception was raised!  Raising original exception for debugging.
Traceback (most recent call last):
  File "hostintel.py", line 193, in <module>
    OTX.add_row(host,row)
  File "/home/cuckoo/keithjjones/hostintel/libs/otx.py", line 84, in add_row
    'reputation')).get('reputation', {})
  File "/usr/local/lib/python2.7/dist-packages/OTXv2.py", line 114, in get
    return self.handle_response_errors(response).json()
  File "/usr/local/lib/python2.7/dist-packages/OTXv2.py", line 97, in handle_response_errors
    raise Exception("Unexpected http code: %r, response=%r", response.status_code, _response_json())
Exception: ('Unexpected http code: %r, response=%r', 404, {'internal_error': 'Unable to decode response json: Expecting value: line 1 column 1 (char 0)'})

**Comment by keithjjones** [comment]
Ok thanks.  Any luck since you posted this?

**Comment by Wulluby** [comment]
Hey, no. I kinda moved on tbh

**Comment by keithjjones** [comment]
Going to close since there weren't more +1's.
