### ISSUE TITLE
Passive Total not authenticating

### ISSUE THREAD

**Issue by marcurdy** [keithjjones/hostintel#11]
I'm getting invalid credentials in search results using a verified email and API key. Perhaps the API has changed slightly?

**Comment by keithjjones** [comment]
That is entirely possible.  I haven't played with this code in a year or two.  Have you done debugging to see where it fails?

**Comment by marcurdy** [comment]
I have the output from your script and validated my credentials only.

**Comment by keithjjones** [comment]
Did you find a workaround for this?

**Comment by marcurdy** [comment]
I did not. I have a working key since I first emailed you to be able to
test. I'm more inclined to want something that works in splunk.
