### ISSUE TITLE
ImportError: No module named geoip2.database

### ISSUE THREAD

**Issue by Skyrant** [keithjjones/hostintel#13]
> python hostintel.py sampleconfig.conf sampledata/smalllist.txt -a >test.csv
Traceback (most recent call last):
  File "hostintel.py", line 21, in <module>
    import libs.geoip
  File "/root/hostintel/libs/geoip.py", line 6, in <module>
    import geoip2.database
ImportError: No module named geoip2.database`

requirements and geoip2 installed with pip.
using Python 2.7.12

**Comment by Skyrant** [comment]
if i use python 3.5.2 i get this error:

> Traceback (most recent call last):
  File "hostintel.py", line 12, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

**Comment by keithjjones** [comment]
That's odd, as I haven't changed the library for geoip since 2016:

https://github.com/keithjjones/hostintel/blob/master/autorequirements.txt

What version do you have installed?

This code isn't Python3 ready.  My later repositories started using Py3 from the get go.
