### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by ocastaneda3** [keithjjones/hostintel#18]
Using Python 3.8.5

> *** Processing 8.8.8.8 ***
ERROR:  An exception was raised!  Raising original exception for debugging.
Traceback (most recent call last):
  File "hostintel.py", line 165, in <module>
    PT.add_row(host,row)
  File "/root/server_logs/hostintel/libs/pt.py", line 64, in add_row
    if whoisdata.has_key('contactEmail'):
AttributeError: 'dict' object has no attribute 'has_key'

From looking around as to why this error is being thrown, the `.has_key()` function was removed in Python3.x

**Comment by ocastaneda3** [comment]
Format Output Better

> *** Processing 8.8.8.8 ***
ERROR:  An exception was raised!  Raising original exception for debugging.
Traceback (most recent call last):
  File "hostintel.py", line 165, in <module>
    PT.add_row(host,row)
  File "/root/server_logs/hostintel/libs/pt.py", line 64, in add_row
    if whoisdata.has_key('contactEmail'):
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by keithjjones** [comment]
I don't doubt that.  When I wrote this, Py2 was the standard.  If you want to make a merge request with the changes for Py3 to work, I'll merge them in.  Thanks!

**Comment by keithjjones** [comment]
Try the code in that MR and see if that doesn't fix the issue for you?  If it does, I'll merge in.

**Comment by ocastaneda3** [comment]
That seemed to do the trick. Went through the list of sources pulling data and came across some other issues using the Python3 fixes. 

On the `OTX by AlienVault Lookup` I ened up getting this error:

> *** Processing 8.8.8.8 ***                                                                   
*** Processing 8.8.4.4 ***                                                                   
*** Processing 192.168.1.1 ***                                                               
*** Processing 10.0.0.1 ***                                                                  
*** Processing google.com ***                                                                
ERROR:  An exception was raised!  Raising original exception for debugging.                  
Traceback (most recent call last):                                                           
  File "hostintel.py", line 193, in <module>                                                 
    OTX.add_row(host,row)                                                                    
  File "/root/server_logs/hostintel/libs/otx.py", line 83, in add_row                        
    otxrepdata = self.otx.get(self.domainurl.format(host,                                    
  File "/usr/local/lib/python3.8/dist-packages/OTXv2.py", line 185, in get                   
    return self.handle_response_errors(response).json()                                      
  File "/usr/local/lib/python3.8/dist-packages/OTXv2.py", line 164, in handle_response_errors
    raise NotFound()                                                                         
OTXv2.NotFound: 'Not Found'                                                                  

There was a similar issue (Issue: #10) raised about this error but don't think a solution was found.

Then on `ThreatCrowd Lookup` it seems to hang for a while on the first lookup with no progress but I assuming it's still processing.

Tested on the small sample set.

Other than that it looks good. Thanks!

**Comment by keithjjones** [comment]
I just pushed a check in the same MR that should fix the OTX error.  See if that helps?

**Comment by ocastaneda3** [comment]
Yep that did the trick. Awesome!

**Comment by keithjjones** [comment]
Yay, merging.  Thanks for your help!
