### ISSUE TITLE
DNS lookup

### ISSUE THREAD

**Issue by Scoston** [keithjjones/hostintel#3]
When doing DNS with URL sometimes you get  127.0.0.1 instead of the IP.

**Comment by keithjjones** [comment]
@Scoston I don't understand.  Can you give me example input and output?

**Comment by Scoston** [comment]
When looking at a several URL the IPV4 column has the 127.0.0.1 displayed instead of the IP that the site resolves to. I ran 5 urls one came back with an IP other than  127.0.0.1. I am running -dvsocr when I execute.

**Comment by keithjjones** [comment]
Well it only works on domain, hostnames, and ip address inputs so I'm not sure how you are feeding it a URL?  URLs aren't supported.  Just the hostnames work.  I may do a URL tool later on.

**Comment by Scoston** [comment]
Thanks, I was www.npec.com and I get returns back.

**Comment by keithjjones** [comment]
Ok, sounds great @Scoston.  I'll close this now.  Reopen if I didn't address what you needed.
