### ISSUE TITLE
VT Response code exception, unknown cause.

### ISSUE THREAD

**Issue by ryanshuck** [keithjjones/hostintel#4]
Occurred at line 734 in file of 13,779 lines. 

ERROR:  An exception was raised!  Raising original exception for debugging.
Traceback (most recent call last):
  File "/Users/submitter/Desktop/hostintel/hostintel.py", line 158, in <module>
    VT.add_row(host,row)
  File "/Users/submitter/Desktop/hostintel/libs/vt.py", line 50, in add_row
    while vtresponse["response_code"] != 200 and vtresponse["response_code"] != 403:
KeyError: 'response_code'

**Comment by keithjjones** [comment]
I will add code that will treat this connection like it never happened, and try again.  Test after I submit please and let me know how it works.

**Comment by keithjjones** [comment]
Give either "master" or "devel" branches a test, and let me know if this fixes the issue for you.  If it does, click "Close" below.  Thanks!

**Comment by keithjjones** [comment]
How did your tests go?

**Comment by ryanshuck** [comment]
Haven't seen it come back up. Probably fine to close. In all likelihood it was a connection issue though.
