### ISSUE TITLE
Python 3.4 output displaying b' tag before string in output.csv file

### ISSUE THREAD

**Issue by acd62081** [keithjjones/hostintel#8]
Keith,
Let me start off by saying that I am a complete newbie with Python and Github. I love this tool but I am having trouble with an extra b' tag being inserted at the beginning of each column in the output.csv file.
I had other issues also, but was able to resolve them.  

I have listed the errors that I that encountered when using Python 3.4 along with the fixes that I used to get hostintel to run. However, I have not been able to resolve Error Number 4 (which seems like it should be simple, I just can't find the answer).  

A github link to the full output.csv results are located at the bottom of the post.

Thank you in advance!

Running HostIntel on Windows 10 with Python v3.4
In order to get HostIntel to run I had to make the following changes in the hostintel.py file.

**1. Error 1:**
Traceback (most recent call last):
  File "hostintel.py", line 12, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'
****Note: ConfigParser in Python 3 has been renamed to configparser
Reference: https://docs.python.org/2/library/configparser.html

	1.a Fix:
	    Change ConfigParser to configparser

**2. Error 2:**
Traceback (most recent call last):
  File "hostintel.py", line 68, in <module>
    ConfigFile = ConfigParser.ConfigParser()
NameError: name 'ConfigParser' is not defined

	2.a Fix:
	    Line 68 change ConfigFile = configparser.configparser() to ConfigFile = configparser.ConfigParser()

**3. Error 3:**
*** Processing 72.21.91.8         ***
Input Host,Country,Postal,City,State,Lat,Long,VirusTotal Detected URLs,VirusTotal Detected Communicating Samples,VirusTotal Detected Downloaded Samples,VirusTotal Link
ERROR:  An exception was raised!  Raising original exception for debugging.
Traceback (most recent call last):
  File "hostintel.py", line 212, in <module>
    output.writerow([unicode(field).encode('utf-8') for field in row])
  File "hostintel.py", line 212, in <listcomp>
    output.writerow([unicode(field).encode('utf-8') for field in row])
NameError: name 'unicode' is not defined

	3.a Fix:
	    Line 212 change unicode to str
	    original version: output.writerow([unicode(field).encode('utf-8') for field in row]) 
	    modified version: output.writerow([str(field).encode('utf-8') for field in row])

**4. Error 4, This is the output problem:**
Output after running hostintel:

Input Host  b'72.21.91.8        '
Country  b''

**Command Line output when running hostintel.py:**
C:\hostintel-master\hostintel-master>python hostintel.py -v -o ConfigurationFile.conf InputFile.conf > output.csv
*** Processing 72.21.91.8         ***
*** Processing 40.97.118.178 ***
*** Processing 72.21.91.29 ***
*** Processing 104.16.27.216 ***
*** Processing 198.41.214.184 ***
*** Processing do-2              ***
*** Processing msnbot-65-52-108-197 ***
*** Processing msnbot-65-52-108-190 ***
*** Processing a-0001 ***
*** Processing 8.18.25.22 ***

**Complete file results located at:**
https://github.com/acd62081/hello-world/blob/master/output.csv

**Comment by keithjjones** [comment]
Try using Python 2 and I think most of these errors will disappear.  I don't think I made this one Python3 ready, yet.

**Comment by acd62081** [comment]
Keith, It does work with python 2.7. 
Thank you.

**Comment by keithjjones** [comment]
No problem.  I'll close this out.  Reopen if I closed it prematurely.
