### ISSUE TITLE
Make Python 3 compatible

### ISSUE THREAD

**Issue by keithjjones** [keithjjones/hostintel#9]
This is a note for myself, for when I have time.

**Comment by keithjjones** [comment]
The issue is configparser.

**Comment by bbbbbrie** [comment]
Hello, there! I have addressed the configparser issue and identified other aspects of hostintel.py that are not Python 3 compatible. I am happy to finish this work and issue a pull request. Before I proceed: would you prefer to maintain backwards compatibility for Python 2.X or is it OK to make changes that will make this Python 3-only?

**Comment by keithjjones** [comment]
Awesome! Thanks! If you can include 2, that's great but I think most people will use 3.

**Comment by bbbbbrie** [comment]
Thank you for the feedback! I have filed a pull request with a few commits that should address this issue and hopefully lead to its resolution!

**Comment by keithjjones** [comment]
You rock, thanks!
